services:
  python-reader:
    privileged: true
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    build:
      context: ./python
    volumes:
      - .:/workspace 
      - /tmp/.X11-unix:/tmp/.X11-unix         
    networks:
      - robot-net
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
      - NET_ADMIN
    environment:
      - DISPLAY=${DISPLAY}
    command: /bin/bash -c "sleep infinity"
  cpp-reader:
    build:
      context: ./cpp
    volumes:
      - .:/workspace           # Mount the entire project to /workspace
    networks:
      - robot-net
    command: /bin/bash -c "sleep infinity"

  cross-compile:
    build:
      context: .
      dockerfile: cross-compile/Dockerfile
    volumes:
      - .:/workspace
    networks:
      - robot-net
    command: /bin/bash -c "sleep infinity"

networks:
  robot-net:
    driver: bridge
