version: "3.8"
services:
  python-reader:
    build:
      context: ./python
    volumes:
      - .:/workspace           # Mount the entire project to /workspace
    networks:
      - robot-net
    command: /bin/bash -c "sleep infinity" #python3 python/read_data.py  # Adjusted path for read_data.py

  cpp-reader:
    build:
      context: ./cpp
    volumes:
      - .:/workspace           # Mount the entire project to /workspace
    networks:
      - robot-net
    command: /bin/bash -c "sleep infinity"
  cross-compile:
    build:
      context: .
      dockerfile: cross-compile/Dockerfile
    volumes:
      - .:/workspace
    networks:
      - robot-net
    command: /bin/bash -c "sleep infinity"

networks:
  robot-net:
    driver: bridge
