version: "3.8"
services:
  python-reader:
    build:
      context: ./python
    volumes:
      - .:/app             # Mounts the entire project directory to /app
      - ./data:/data       # Mounts the local data directory to /data in the container
    networks:
      - robot-net
    command: python3 /app/read_data.py

  cpp-reader:
    build:
      context: ./cpp
    volumes:
      - .:/app             # Mounts the project folder to /app for consistency
      - ./data:/data       # Mounts the local data directory to /data in the container
    networks:
      - robot-net
    command: /bin/bash -c "./read_data"

  cross-compile:
    build:
      context: .
      dockerfile: cross-compile/Dockerfile
    volumes:
      - .:/app             # Optional: mount project directory if needed
      - ./output:/output   # Mounts the output directory for compiled files
    networks:
      - robot-net
    command: /bin/bash -c "sleep infinity"

networks:
  robot-net:
    driver: bridge
