version: "3.8"
services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    network_mode: service:python-reader
    command: sleep infinity

  python-reader:
    build:
      context: ../python
    volumes:
      - ../data:/data
    networks:
      - robot-net

  cpp-reader:
    build:
      context: ../cpp
    volumes:
      - ../data:/data
    networks:
      - robot-net

  cross-compile:
    build:
      context: ..
      dockerfile: cross-compile/Dockerfile
    volumes:
      - ../output:/output
    networks:
      - robot-net

networks:
  robot-net:
    driver: bridge
